spring:
  application:
    name: order-service
  profiles:
    active: dev

---
# ===== DEV (H2) =====
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:h2:mem:ordersdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080


---
# ===== PROD (PostgreSQL) =====
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO}
server:
  port: 8080
